### ISSUE TITLE
Tests passing, but with a stacktrace at the end

### ISSUE THREAD

**Issue by eirnym** [jsonschema2dataclass/js2d-gradle#681]
Stacktrace: 

```java
org.gradle.process.internal.ExecException: Process 'X' finished with non-zero exit value 143
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.waitForStop(DefaultWorkerProcess.java:220)
        at org.gradle.process.internal.worker.DefaultWorkerProcessBuilder$MemoryRequestingWorkerProcess.waitForStop(DefaultWorkerProcessBuilder.java:284)
        at org.gradle.process.internal.worker.DefaultMultiRequestWorkerProcessBuilder$1.stop(DefaultMultiRequestWorkerProcessBuilder.java:173)
        at org.gradle.workers.internal.WorkerDaemonClient.stop(WorkerDaemonClient.java:59)
        at org.gradle.workers.internal.WorkerDaemonClientsManager.stopWorkers(WorkerDaemonClientsManager.java:164)
        at org.gradle.workers.internal.WorkerDaemonClientsManager.stop(WorkerDaemonClientsManager.java:124)
        at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:635)
        at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:635)
        at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:635)
        at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:635)
        at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:635)
        at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
        at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.stop(DefaultServiceRegistry.java:635)
  ```

**Comment by eirnym** [comment]
As per little investigation, this is happening if I have at least 3 tests  and each of them are run against several gradle versions

**Comment by eirnym** [comment]
one of the tests has shown following addition:

```java
Caused by: java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:231)
	at org.gradle.process.internal.shutdown.ShutdownHooks.removeShutdownHook(ShutdownHooks.java:33)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:208)
	at org.gradle.process.internal.DefaultExecHandle.aborted(DefaultExecHandle.java:368)
	at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:108)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:84)
```

**Comment by eirnym** [comment]
Full log [4_Build Plugin (17, temurin).txt](https://github.com/jsonschema2dataclass/js2d-gradle/files/10888991/4_Build.Plugin.17.temurin.txt)

**Comment by eirnym** [comment]
I'm not observing the issue anymore. Plrobably issue has been fixed.
